# Generated by Django 3.0.8 on 2020-07-22 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_tutors', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
