# Generated by Django 3.0.8 on 2020-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credentials',
            field=models.FileField(blank=True, null=True, upload_to='docs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
