# Generated by Django 3.0.8 on 2020-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200713_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='api.SubjectsRating'),
        ),
    ]
