# Generated by Django 3.0.8 on 2020-07-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschedule',
            name='grade',
            field=models.CharField(default='maths', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='subject',
            field=models.CharField(default='maths', max_length=120),
            preserve_default=False,
        ),
    ]
