# Generated by Django 3.0.8 on 2020-07-16 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_days_studentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 4, 21, 59, 542723, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
