# Generated by Django 3.0.8 on 2020-07-23 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200723_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 12, 29, 31, 601616)),
        ),
    ]
