# Generated by Django 3.0.8 on 2020-07-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200713_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
