# Generated by Django 3.0.8 on 2020-07-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='c0961f02c2d1401ab8c9572e87324de4', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
