# Generated by Django 3.0.8 on 2020-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='1ca31b46c4f', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
