# Generated by Django 3.0.8 on 2020-07-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='5a32cb5b104149849cd0b15380f28c33', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
