# Generated by Django 3.0.8 on 2020-07-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200714_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='fb2e3c50bc9342ed9c9fed1720808237', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
