# Generated by Django 3.0.8 on 2020-07-15 03:10

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('accounts', 'CustomUser')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_uuid_field'),
    ]

    operations = [

    	migrations.RunPython(gen_uuid, 
reverse_code=migrations.RunPython.noop),
    ]
