# Generated by Django 3.0.8 on 2020-07-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200714_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='c3d26e8959b64a15bc5a56ec96b9a83d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
