# Generated by Django 3.0.8 on 2020-07-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
