# Generated by Django 3.0.8 on 2020-07-15 03:10

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_uuid_values'),
    ]

    operations = [
	    migrations.AlterField(
	            model_name='customuser',
	            name='id',
	            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
	        ),
    ]
