# Generated by Django 3.0.8 on 2020-07-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_timestamp'),
        ('accounts', '0004_delete_userlogin'),
    ]

    operations = [
    ]
