name: Android Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Fix Android SDK
        run: sudo chmod -R a+w /usr/local/Caskroom/android-sdk

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble